name: cardly
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  go_router: ^12.1.1
  riverpod_annotation: ^2.1.6
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/spaceMono.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
